"""
transcript_correction.py

Two-step transcript fix:
  1. context_correct_transcript() — GPT reads the full transcript and fixes
                                    words that are clearly wrong based on
                                    linguistic/situational context alone.

  2. brand_correct_transcript()   — uses on-screen caption text to fix brand
                                    names, product names, and proper nouns.
"""

from connection import ask_ai, ask_ai_images


# ---------------------------------------------------------------------------
# Pre-transcription: extract hint words from frames for Whisper prompt
# ---------------------------------------------------------------------------

def extract_hint_words(frames: list) -> str:
    """
    Quickly scan a few video frames and return a comma-separated list of
    key words (animal names, people names, brand names, products) visible
    in the video. These are passed to Whisper as prompt hints so it
    transcribes them correctly from the start.

    Returns a short comma-separated string, e.g. "dog, Leo, Troy, collagen"
    Returns "" if nothing useful is found or on any error.
    """
    if not frames:
        return ""

    images_base64 = [f["base64"] for f in frames if f.get("base64")]
    if not images_base64:
        return ""

    prompt = """Look at these video frames.

List ONLY the specific words that are important for accurate transcription:
- Names of people or pets visible or mentioned
- Brand names or product names
- Animals shown (e.g. dog, cat)
- Any unusual or domain-specific words

Rules:
- Output ONLY a short comma-separated list of words. Example: dog, Leo, Troy, collagen, Koocester
- Do NOT include common everyday words
- Do NOT include descriptions or sentences
- Maximum 30 words total
- If nothing useful, output nothing

Output the word list only:"""

    try:
        result = ask_ai_images(prompt, images_base64)
        words = [w.strip() for w in result.strip().split(",") if w.strip()]
        words = [w for w in words if len(w) < 30]
        return ", ".join(words[:30])
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Step 1 — Context-aware correction
# ---------------------------------------------------------------------------

def context_correct_transcript(raw_transcript: str) -> str:
    """
    Use GPT to fix Whisper mishearings based purely on linguistic and
    situational context — no OCR needed.

    Returns the corrected transcript, or the original if anything goes wrong.
    """
    if not raw_transcript.strip():
        return raw_transcript

    prompt = f"""You are fixing transcription errors in a video transcript.

The transcript was auto-generated by Whisper from a video with Singaporean or
Malaysian accented English. Whisper sometimes mishears words due to the accent.

Your job:
- Fix words that are CLEARLY wrong and make no sense in context.
- Common error: similar-sounding words swapped due to accent.
  Example: "one door two door" in a conversation about pets → "one dog two dog"

STRICT RULES — never break these:
- Do NOT touch any numbers, currencies, or amounts. Leave RM, SGD, dollar
  figures, percentages, and all numeric values exactly as they are.
- Do NOT change people's names, pet names, or place names.
- Do NOT rephrase, restructure, or improve the transcript.
- Do NOT add or remove punctuation.
- Do NOT summarise or shorten the transcript.
- Only fix a word if you are highly confident it is wrong from context.
- If you are unsure, leave it unchanged.
- Return ONLY the corrected transcript text — nothing else.

TRANSCRIPT:
{raw_transcript[:3000]}

CORRECTED TRANSCRIPT:"""

    try:
        corrected = ask_ai(prompt).strip()

        if len(corrected) < len(raw_transcript) * 0.3:
            return raw_transcript

        return corrected
    except Exception:
        return raw_transcript


# ---------------------------------------------------------------------------
# Step 2 — OCR: extract on-screen speech captions from frames
# ---------------------------------------------------------------------------

def extract_onscreen_text(frames: list, batch_size: int = 20) -> str:
    """
    Send video frames to GPT-4o vision and return all speech caption/subtitle
    text found on screen. Processes frames in batches.
    """
    if not frames:
        return ""

    images_base64 = [f["base64"] for f in frames if f.get("base64")]
    if not images_base64:
        return ""

    prompt = """Look at these video frames carefully.

Your job: extract ONLY speech caption / subtitle text — text that shows what
people are saying (burned-in or auto-generated captions).

Rules:
- Only extract speech captions / subtitles.
- IGNORE completely:
    * Watermarks and channel logos (e.g. "Koocester" repeated across frames)
    * Persistent overlays in the same screen position across many frames
    * Decorative text, graphic titles, CTAs, end cards, product labels
- List each unique caption line once, one per line.
- Do NOT describe visuals or add commentary.
- If a frame has no speech captions, skip it silently.

Just output the caption text, nothing else."""

    all_lines = []
    seen = set()

    for i in range(0, len(images_base64), batch_size):
        batch = images_base64[i:i + batch_size]
        try:
            result = ask_ai_images(prompt, batch)
            for line in result.strip().splitlines():
                line = line.strip()
                if line and line.lower() not in seen:
                    seen.add(line.lower())
                    all_lines.append(line)
        except Exception:
            continue

    return "\n".join(all_lines)


# ---------------------------------------------------------------------------
# Step 3 — Brand name correction using OCR
# ---------------------------------------------------------------------------

def brand_correct_transcript(transcript: str, onscreen_text: str) -> str:
    """
    Use OCR'd caption text to fix brand names, product names, and proper nouns.

    Returns the corrected transcript, or the original if anything goes wrong.
    """
    if not transcript.strip() or not onscreen_text.strip():
        return transcript

    prompt = f"""You are fixing brand names and proper nouns in a video transcript.

The transcript has already been corrected for common mishearings. Now fix ONLY
brand names, product names, place names, or proper nouns that appear in the
on-screen captions but are wrong or missing in the transcript.

STRICT RULES — never break these:
- Only fix brand names, product names, and proper nouns.
- Do NOT fix regular words — those were handled in a previous pass.
- Do NOT replace people's names or pet names with brand/channel names.
  Example: do NOT replace a pet name like "Troy" with "Koocester" just because
  "Koocester" appears as a watermark in the captions.
- Do NOT use watermark text or channel logos as corrections.
- Keep ALL other words exactly as they are.
- Do NOT rephrase, restructure, add punctuation, or shorten.
- If unsure, leave the original word unchanged.
- Return ONLY the corrected transcript text — nothing else.

ON-SCREEN CAPTIONS (for brand name reference only):
{onscreen_text[:2000]}

TRANSCRIPT TO FIX:
{transcript[:3000]}

CORRECTED TRANSCRIPT:"""

    try:
        corrected = ask_ai(prompt).strip()

        if len(corrected) < len(transcript) * 0.5:
            return transcript

        return corrected
    except Exception:
        return transcript
